### ISSUE TITLE
tut4 memory

### ISSUE THREAD

**Issue by michaelworcester** [ShabbyX/vktut#2]
> - If the memory is not host-coherent, then we need to flush application writes, invalidate application caches
>   - before reads, and insert memory barriers after device writes.  For the sake of simplicity, as this tutorial
>   - is already huge, let's just ask for host-coherent memory.  Such a memory may not be available on all
>   - devices, so ideally you would want to look for host-coherent memory, and if not found be prepared to do the
>   - above flushes, cache invalidations and barriers.

Even with coherent memory you must still insert the appropriate memory barriers after device writes (and indeed, before device reads (note: QueueSubmit effectively performs an implicit invalidate)).

All devices **must** support at least one memory type that is coherent.

**Comment by ShabbyX** [comment]
Thank you again for pointing out these incorrect statements. I addressed your issues here: cc5b5e305222cba0e7e5c770b562eb96b380bfe7

Vulkan says:

> Note that such a barrier is performed implicitly upon each command buffer submission, so an explicit barrier is only rarely needed (e.g. if a command buffer waits upon an event signaled by the host, where the host wrote some data after submission). For device writes to be seen by subsequent host reads, a pipeline barrier is required to make the writes visible.

It says that explicit barriers are rare, and at the same time it seems that there is no implicit barrier on termination of the command so a pipeline barrier would be necessary if the host wants to read something the device has written. Is my understanding correct? If so I should add a barrier to tut4, since the application reads back the buffer modified by the GPU to validate correct behavior.

**Comment by michaelworcester** [comment]
The barrier is only rarely needed from HOST -> DEVICE, it's always needed from DEVICE -> (DEVICE | HOST).
