### ISSUE TITLE
Configure script fails

### ISSUE THREAD

**Issue by Smaloki** [ShabbyX/vktut#6]
When I try to run the configure script, it works fine except for these three output lines:
`checking vulkan/vulkan.h usability... no`
`checking vulkan/vulkan.h presence... no`
`checking for vulkan/vulkan.h... no`

Then it exits with this message:
`configure: error: Vulkan header not found`

I downloaded the Vulkan SDK directly from LunarG, let the self-extracting archive do its thing and then followed the setup instructions in the Getting_Started.html file included in the SDK.
I set up my environment variables by adding these lines to my .bashrc file:
`VULKAN_SDK=~/VulkanSDK/1.0.17.0/x86_64`
`export PATH=$PATH:$VULKAN_SDK/bin`
`export LD_LIBRARY_PATH=$VULKAN_SDK/lib`
`export VK_LAYER_PATH=$VULKAN_SDK/etc/explicit_layer.d`

I've also tried copying "explicit_layer.d" directly into my "~/.local/share/vulkan/" directory and copying the "/vulkan/" directory that contains the header files directly into "/usr/include/". The former had no effect whatsoever, the latter removed the first two lines, but then threw an error that it couldn't find the Vulkan library.

I'm running Ubuntu 16.04 (4.4.0-28-generic), using an Nvidia GTX 760 with the proprietary drivers (version 364.16). I can confirm that Vulkan works on my system, I've ran "vulkaninfo" and tried "The Talos Principle".

I'm not sure what to do and while I'm fairly certain that I missed something obvious, I'm simply out of ideas... thanks in advance for any tips!

**Comment by ShabbyX** [comment]
Hi,

Thanks for moving your question here. The solution is quite simple. See, `autoconf` is looking for `vulkan/vulkan.h` in standard header locations. The environment variables you have set seem to be for the sake of the Vulkan Common Loader.

Since you haven't installed Vulkan in standard locations (for example installing the headers in `/usr/include/vulkan/*.h`), `autoconf` is not able to find it.

There are two courses of action here:
1. Give flags to the configure script, for example:
   
   ```
   ./configure CPPFLAGS="-I/path/to/vk/include/" LDFLAGS="-L/path/to/vk/lib/"
   ```
2. I could take a look at `VULKAN_SDK` variable and try to infer these locations myself.

I'll go with automatically finding the header files based on that environment variable, even though it's not how one best uses `autoconf`. In the meantime, you can go ahead with the first solution.

**Comment by Smaloki** [comment]
Thanks! I didn't have time to try the first solution yet and since it looks as though you already updated the script, I'll just quickly download the project folder again (seems like there have been a few other commits as well).

**Comment by ShabbyX** [comment]
@Smaloki Hope it works on your side :)

You can always clone the repository with `https` and just `git fetch origin` followed by `git merge origin master` to get the latest changes. If you know git that is.
